language: python
sudo: false
python:
  - "3.4"
  - "3.2"
  - "2.7"
env:
  - REQ='Django>=1.7,<1.8'
  - REQ='Django>=1.8,<1.9'
matrix:
install:
  - pip install -q $REQ flake8
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp && flake8 ."
